### ISSUE TITLE
Aggregate Polar data if not in study

### ISSUE THREAD

**Issue by s-mueller** [sealuzh/PersonalAnalytics#106]
To reduce the amount of data that is captured, we should aggregate the data per minute if we're not collecting the data in a study setting.

**Comment by casaout** [comment]
Suggestion: create setting "IsDetailedCollectionEnabled" that can be enabled via Pilot-Deployments (similar to UserInputTracker). If enabled: store detailed data (default: disabled), if enabled: store detailed (per second) and aggregate.
