### ISSUE TITLE
Bug: Pausing/Continuing Tracker doesn't work anymore on Biometrics-branch

### ISSUE THREAD

**Issue by casaout** [sealuzh/PersonalAnalytics#111]

**Comment by s-mueller** [comment]
Did you already verify that it's a problem of the biometric branch? Or does this happen on other branches too?

**Comment by casaout** [comment]
yes, it works on the dev branch. Thanks!

**Comment by s-mueller** [comment]
I think this commit should fix the issue. I tested it on my system and there it works now.
