### ISSUE TITLE
SSL Encryption for Data Transfer

### ISSUE THREAD

**Issue by casaout** [sealuzh/PersonalAnalytics#125]
- [ ] Implement
- [ ] Test using Fiddler / Wireshark

**Comment by s-mueller** [comment]
We ordered a SSL certificate that we should get in a couple of days.

**Comment by s-mueller** [comment]
Still waiting for the certificate.

**Comment by s-mueller** [comment]
We can start implementing this change at 20.04.17

**Comment by s-mueller** [comment]
Finally it is implemented! The web services are now encrypted and our websites are available over https.

There is one issue that we have to fix as soon as Manu's study is done: https://github.com/sealuzh/FlowTracker/issues/41
