### ISSUE TITLE
Settings: Enable/Disable trackers should run CreateTablesIfNotExists

### ISSUE THREAD

**Issue by casaout** [sealuzh/PersonalAnalytics#130]
- [ ] check if it's done
- [ ] check if switch between detailed/not detailed logging has all necessary tables (for UserInputTracker, FitbitTracker, PolarTracker)

**Comment by s-mueller** [comment]
Checked. All the trackers call the method, except UserEfficiencyTracker and WindowsActivityTracker. But that's okay.
