### ISSUE TITLE
Test move from Pilot-Branch to Master-Branch

### ISSUE THREAD

**Issue by casaout** [sealuzh/PersonalAnalytics#131]
We can currently imagine the following issues:
- [x] can we install an app with a lower version number? (master version is usually lower)
- [ ] are there database-versioning issues? (e.g. db-table update on Pilot (that in turn updates the DB-version), move to master which doesn't yet have the db-update (but the DB is already on the new version) - conflicts expected!

**Comment by s-mueller** [comment]
I just tested the first part. That's no problem, if we use the same build to build the master branch. If we do that, the build number increases as it would normally do, but instead of building a specific branch, we just build the master branch.

**Comment by s-mueller** [comment]
The second issue is definitively a problem and can imho only be avoided if we don't update the database as long as there are people in the pilot. As soon as we have an update to master, we can change the DB version.
