### ISSUE TITLE
Merge Dev-Branch to Master

### ISSUE THREAD

**Issue by casaout** [sealuzh/PersonalAnalytics#136]
- [x] Cherry-picks: https://github.com/sealuzh/PersonalAnalytics/commit/25630b6e4892f853d0f6e06f44013257da4d2bdf and https://github.com/sealuzh/PersonalAnalytics/commit/5b250025d3d6d3f6b1d0c8bf822bdd0d701d5bc3 and  (+ others?)
- [x] Make fix on dev/master as well: https://github.com/sealuzh/PersonalAnalytics/commit/1fe0d1849a716fd4e99e0de16184a22bf0579b8b#diff-0e2b8b5bdbe2ba313b0e7a0e55d18b59R106
- [x] what else?
- [x] merge
- [x] test
- [ ] party

**Comment by s-mueller** [comment]
Are there any open issues in the dev branch that we should fix before merging to master?
