### ISSUE TITLE
Find out why the DB Browser for SQLite cannot show all tables in the "Browse Data"-View

### ISSUE THREAD

**Issue by casaout** [sealuzh/PersonalAnalytics#140]

**Comment by s-mueller** [comment]
I couldn't find an issue here: https://github.com/sqlitebrowser/sqlitebrowser/issues

We should figure out how to reproduce this bug and then submit an issue.

**Comment by casaout** [comment]
interestingly with 3.9.1 I cannot reproduce the bug anymore...
