### ISSUE TITLE
Office365 authentication is popping up all the time when authentication is cancelled

### ISSUE THREAD

**Issue by manulita** [sealuzh/PersonalAnalytics#142]
To reproduce:

1) enable Office365 tracker via settings, but close the window with the authentication without filling it out.
2) wait 1-2 minutes
3) the authentication window will pop up again and again, as soon as you close it there is a new one. this doesn't stop even if you disable the tracker again via the settings. needed to restart the application to get rid of the popups.

I found this during testing in my study branch.

**Comment by s-mueller** [comment]
In the first screen window we just set the settings in the database to disabled. Probably we also have to indicate that the tracker should not try to authenticate in these cases.

**Comment by s-mueller** [comment]
I tried to fix this and I guess I found a solution that works but @casaout it would be good if you have a look at it after your holidays to make sure we don't introduce any other unwanted behaviour with the fix.

The only thing I changed is adding a return in this part of the start method. Is there any reason why we should execute the rest of the start method when the authentication failed?

```
if (!isAuthenticated)
{
   IsRunning = false;
   var msg = string.Format(...);
   MessageBox.Show(msg, Dict.ToolName + ": Error", MessageBoxButton.OK);

   return;
}
```

**Comment by s-mueller** [comment]
@manulita I applied the changes to the dev-am and the study branch, please test.

**Comment by s-mueller** [comment]
This bug is not yet fixed 100%. Steps to reproduce:

Start PA with MsOfficeTracker enabled in the settings. When asked about login click on Cancel. Then open the retrospection and the Login window will show again and again, even when I pressed cancel multiple times.

**Comment by s-mueller** [comment]
The problem is that when clicking on cancel, we set the IsRunning flag to false, but the tracker is still enabled. Then, when the retrospection is loaded. The MsOfficeTracker is asked whether it is enabled and returns true. I guess when opening the retrospection we should rather check for IsRunning then for IsEnabled?

**Comment by s-mueller** [comment]
I changed the code like mentioned above for the study branch. @casaout  please have a look and if ok, we can copy it to the other branches

**Comment by casaout** [comment]
It's difficult to think about all the scenarios, but I think the two changes fixed this bug. And I currently don't think there were new bugs introduced. Thanks @s-mueller!

Let's observe the behavior for a little while.

**Comment by s-mueller** [comment]
Ok, then I apply https://github.com/sealuzh/PersonalAnalytics/commit/cff12229366eebe6ec201e573a3a7d8627e525b7#commitcomment-21349955 to the dev branch as well
