### ISSUE TITLE
'CallbackOnCollectedDelegate' when resuming PA

### ISSUE THREAD

**Issue by s-mueller** [sealuzh/PersonalAnalytics#143]
Steps to reproduce:

1. Start PA with MsOfficeTracker enabled but not logged in
2. When asked to log in, click on cancel
3. Pause tracker
4. Resume tracker
5. A message box will appear that tells you that the MsOfficeTracker was disabled. Without clicking on OK, resume PA.

--> PA crashes.

> CallbackOnCollectedDelegate occurred
> Message: Managed Debugging Assistant 'CallbackOnCollectedDelegate' has detected a problem in 'C:\Users\seal\PersonalAnalytics\src\client\AM.PA.MonitoringTool\PersonalAnalytics\bin\Debug\PersonalAnalytics.vshost.exe'.
> Additional information: A callback was made on a garbage collected delegate of type 'WindowsActivityTracker!WindowsActivityTracker.Helpers.NativeMethods+WinEventDelegate::Invoke'. This may cause application crashes, corruption and data loss. When passing delegates to unmanaged code, they must be kept alive by the managed application until it is guaranteed that they will never be called.
> 

```
System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  InnerException: 
```

In the first line of method  private async Task<bool> SignIn() in Office365API

**Comment by s-mueller** [comment]
@manulita fyi if this bug should every occur

**Comment by casaout** [comment]
what do you mean with "5. ... resume PA"? - open the retrospection?

Isn't this bug now fixed with https://github.com/sealuzh/PersonalAnalytics/issues/142?

**Comment by s-mueller** [comment]
Unpause/Resume PersonalAnalytics from the context menu

**Comment by casaout** [comment]
I cann reproduce the bug already with step 5. When I debug it trough step by step, it doesn't crash, but when it just runs, the log-in window is not shown, and then it somehow crashes...
