### ISSUE TITLE
The error log is full with errors from the MsOfficeTracker when no credentials are inserted

### ISSUE THREAD

**Issue by s-mueller** [sealuzh/PersonalAnalytics#145]
The error log is full with the following errors. Imho this exception is expected if the MsOfficeTracker can't login. Is there a need to still log it? It makes it difficult to find the real errors.

> Log Entry: 3:22:24 PM Friday, March 10, 2017
> Exception of type 'Microsoft.Experimental.IdentityModel.Clients.ActiveDirectory.AdalServiceException' was thrown. :    at Microsoft.Experimental.IdentityModel.Clients.ActiveDirectory.AcquireTokenInteractiveHandler.VerifyAuthorizationResult()
>    at Microsoft.Experimental.IdentityModel.Clients.ActiveDirectory.AcquireTokenInteractiveHandler.<PreTokenRequest>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at Microsoft.Experimental.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Experimental.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenCommonAsync>d__4e.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Experimental.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__38.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MsOfficeTracker.Helpers.Office365Api.<SignIn>d__11.MoveNext() in C:\Users\seal\PersonalAnalytics\src\client\AM.PA.MonitoringTool\MsOfficeTracker\Helpers\Office365Api.cs:line 122

**Comment by casaout** [comment]
just log in db and not errors.log

**Comment by casaout** [comment]
Close as it's directly related to: https://github.com/sealuzh/PersonalAnalytics/issues/153
