### ISSUE TITLE
Fitbit authentication window should not be shown when not necessary

### ISSUE THREAD

**Issue by manulita** [sealuzh/PersonalAnalytics#164]
The fitbit authentication window is opened whenever the token needs to be refreshed. The user has to click on OK to close the window, and it pops up around once a day, and can be annoying.
It would be nice to get rid of that by either:

- only refresh the token once a month (we tried that but it doesn't seem to work now)
- close the window programmatically after refreshing the token

**Comment by s-mueller** [comment]
Fixed in the study branch. Please check whether this is okay and if yes, we apply the fix to the master branch.

**Comment by s-mueller** [comment]
@manulita Copied to master branch. Gonna close this one for now.
