### ISSUE TITLE
Make installation easier with ClickOnce & Certificate

### ISSUE THREAD

**Issue by casaout** [sealuzh/PersonalAnalytics#45]
see

http://stackoverflow.com/questions/977621/signing-clickonce-with-a-certificate
https://author.tucows.com/index.php?action=auth&redirect=certs.php

**Comment by s-mueller** [comment]
ClickOnce installation is done, we still have to work on the certificate though.

**Comment by s-mueller** [comment]
Signing with the certificate is also done, now we can focus on the SmartScreen issue.

**Comment by s-mueller** [comment]
I just added a timestamp to the signed files. Without a timestamp, we run into problems when our certificates expire. See: http://stackoverflow.com/questions/4417410/why-should-we-set-a-timestamp-when-we-do-a-codesigning
