### ISSUE TITLE
Nice(r) icon for PersonalAnalytics

### ISSUE THREAD

**Issue by casaout** [sealuzh/PersonalAnalytics#47]
I think it would make sense and be fantastic to get a better icon for PersonalAnaltics.
My suggestion would be to quickly brainstorm about ideas and then ask a designer (e.g. on Fiver or Freelancer.com) to design suggestions.
This could be useful for the website, github page, publications, task tray, etc.
Any ideas/suggestions are welcome!

**Comment by parodeghero** [comment]
Something like one of these would be cool : https://www.iconfinder.com/icons/36961/business_chart_consultant_graph_man_user_icon#size=32

https://www.iconfinder.com/icons/739067/analysis_analytics_chart_charts_diagram_graph_user_icon#size=128

**Comment by casaout** [comment]
@csatterfield Here you find the updated icons (also a black version for Mac): https://github.com/sealuzh/PersonalAnalytics/tree/dev-am/src/client/AM.PA.MonitoringTool/PersonalAnalytics/Assets
