### ISSUE TITLE
Help-Button

### ISSUE THREAD

**Issue by casaout** [sealuzh/PersonalAnalytics#53]
**Idea from @parodeghero:**
I was thinking more about the dashboard and I think it would be nice to have a help button that maybe brings up the starting screen or a simplified tutorial. 

Other:
- We could add it to the retrospection-window and the context-menu of the task-tray icon.
- Also add contact information

**Comment by casaout** [comment]
TODO: we need to discuss how it works/fits/compares to the FirstStartWindow.xaml or if it's the same.

**Comment by parodeghero** [comment]
Discussed :+1:
