### ISSUE TITLE
InteractionDashboard: Figure out how Skype calls duration is recorded in Outlook Conversation History

### ISSUE THREAD

**Issue by parodeghero** [sealuzh/PersonalAnalytics#61]
MS said this isn't a bug.  Now wait for it to be added as a feature or to find a better way of doing this.

http://stackoverflow.com/questions/36899056/get-call-time-in-skype-for-business 

cc: @davidcshepherd

**Comment by parodeghero** [comment]
https://community.office365.com/en-us/f/166/t/441994

**Comment by parodeghero** [comment]
Suggestion for MS.  Please vote for feature if you see this link:  https://office365.uservoice.com/forums/273494-outlook-and-calendar/filters/top?page=2

**Comment by parodeghero** [comment]
We may just incorporate incoming calls for now since we can parse the data for those :)

**Comment by parodeghero** [comment]
I hope MS changes how they are handling this. However, I think we now understand what they are doing when it comes to recording the duration in the Conversation History folder.

**Comment by casaout** [comment]
what did you decide on this? did you hear anything back from MS?

**Comment by parodeghero** [comment]
Since we have the incoming calls duration, I think we should show this as a call.  MS will most likely implement in the way future, but we don't have the time to wait for this.  I will do this later.  So basically the pop up counts the total calls both incoming and outgoing.  The chart shows just the incoming.  We can add outgoing as soon as the get through adding the feature.  I don't feel comfortable tracking this and would like to purely pull the data from Outlook that is already store there :)
