### ISSUE TITLE
MsOfficeTracker - Not enough quota available

### ISSUE THREAD

**Issue by casaout** [sealuzh/PersonalAnalytics#62]
Log Entry: 3:22:09 PM Wednesday, April 27, 2016
Not enough quota is available to process this command :    at MS.Win32.UnsafeNativeMethods.PostMessage(HandleRef hwnd, WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Reported by @tzimmermsr

**Comment by casaout** [comment]
Possible help:
- http://stackoverflow.com/questions/12584619/mysterious-not-enough-quota-is-available-to-process-this-command-in-winrt-port
-  http://stackoverflow.com/questions/20964360/not-enough-quota-is-available-to-process-this-command-wpf 
- https://support.microsoft.com/en-us/kb/327699

**Comment by casaout** [comment]
Need some more details on when (exactly) this exception happens.

- Is this a memory or threading issue? 
- Or, is there an issue with how the window is created?

Some temporary fixes:
-

**Comment by walterlv** [comment]
I am suffering from the same issue, too. As soon as I found your issue, I was so excited that you've posted so many urls to solve this problem.

Thanks to all your contributes to solve this problem. However, I've read all of these urls before and nothing helped, as the same you got several month ago.

Do you have any code that can reproduce this issue? This may help.  
I'm trying to writing such code as your last url ([microsoft](https://support.microsoft.com/en-us/kb/327699)) said.

By the way, I have some other urls below:
- Diagnosis on “Quota Exceeded” Win32Exception  
[http://stackoverflow.com/questions/10086985/diagnosis-on-quota-exceeded-win32exception](http://stackoverflow.com/questions/10086985/diagnosis-on-quota-exceeded-win32exception)
- WPF app fails to start second time  
[https://social.msdn.microsoft.com/Forums/vstudio/en-US/664f2de6-342f-4527-977e-a7e12eac8d90/wpf-app-fails-to-start-second-time-?forum=wpf](https://social.msdn.microsoft.com/Forums/vstudio/en-US/664f2de6-342f-4527-977e-a7e12eac8d90/wpf-app-fails-to-start-second-time-?forum=wpf)

**Comment by casaout** [comment]
hi @walterlv Thank you! Unfortunately, I've had no luck so far to reproduce the issue and it happens only very rarely on some user's machines. This makes it really hard to identify and resolve the issue. Please let me know when you find something new/solve the bug; and I will do likewise. Thanks!

**Comment by zd0214** [comment]
Same issue.. no ideal.

**Comment by casaout** [comment]
Didn't encounter the issue anymore with the new MSAL and updated Graph API. Closing.
