### ISSUE TITLE
Help Window

### ISSUE THREAD

**Issue by parodeghero** [sealuzh/PersonalAnalytics#64]
Have an accordion style help window with information to help the users.  

- [x] Create window

- [ ] Add content

**Comment by parodeghero** [comment]
@casaout I'm considering throwing out this help window.  At least from the side of Focus Light, we will have a help window for both the light and dashboard combined I think.  So then this becomes redundant.  Plus it saves us some time with not creating visual content.   What do you think?

**Comment by casaout** [comment]
@parodeghero I agree. I think it would be better to have the welcome screen and help stuff unified in the FocusLight-project.
