### ISSUE TITLE
MsOfficeTracker - GetNumberOfChatsAndCallsSentOrReceived fails

### ISSUE THREAD

**Issue by casaout** [sealuzh/PersonalAnalytics#66]
The method call to GetNumberOfChatsAndCallsSentOrReceived fails with the message: "Oh No! Conversation Folder failed!". Could you please have a look at it?

Maybe the issue is a translation thing, as my folder is called "Aufgezeichnete Unterhaltungen". When I change the query to this other string, I don't get the error above, but it still doesn't find any chats or calls (even though I have some).

@parodeghero Let me know in case you need more information. Thanks!

**Comment by parodeghero** [comment]
I believe it is a translation problem.  However, I will look more into it once I get a chance.

**Comment by parodeghero** [comment]
It's most definitely a translation problem.  I am going to work on fixing this this week.

**Comment by parodeghero** [comment]
We now have a new issue for making the product work internationally.  I will close this issue.

**Comment by casaout** [comment]
Link: https://github.com/sealuzh/PersonalAnalytics/issues/69
