### ISSUE TITLE
InteractionDashboard: Chat Bug

### ISSUE THREAD

**Issue by casaout** [sealuzh/PersonalAnalytics#76]
From @parodeghero:
"I’m not sure what is going on.  However, since yesterday, my chats are either 0 or not showing up at all even though I did send chats."

**Comment by casaout** [comment]
Questions to consider:
- [ ] Does the meetings stuff work? – If yes, then the office 365 api stuff is generally fine…
- [ ] Does the email stuff work (sent/received, etc.) generally? – If yes, then fetching emails is fine.
- [ ] What happens when you debug through? – do you just not receive any results when querying the API or is there an exception?

**Comment by parodeghero** [comment]
MS changed stuff on Conversation History messages.  Updated regex and made it more flexible.

**Comment by casaout** [comment]
cool, good to hear you could fix it!
