### ISSUE TITLE
MsOfficeTracker - Also count total number of inbox items

### ISSUE THREAD

**Issue by casaout** [sealuzh/PersonalAnalytics#81]
via @tzimmermsr 

Add a column to count the total number of emails in the inbox (besides counting the number of unread items), to make both types of people happy:

(1) people who treat unread emails as actions items, and 
(2) who treat any item in the inbox as action item (no matter if read of nor)

**Comment by tzimmermsr** [comment]
Please add another column for emails received *and* read (across all folders).

This should be a subset of the received number that is currently collected.

Thanks,
Tom

**Comment by casaout** [comment]
@tzimmermsr This would be a count of all received emails for a date, which are in the "unread" state?

**Comment by tzimmermsr** [comment]
Yes.

“Received” and “Received and Unread” then allow us to infer the number of “Read” emails.

**Comment by casaout** [comment]
- [ ] Received and Unread => read
- [ ] Total number of inbox (besides unread in inbox) => performance?
